name: self_finance
description: It is a finance data storing app. Which help the user to save there coustomer details and calculate the intrest in real time, It is an offline app so the data will be safe inside the device , this app can run in windows, Andriod and IOS.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7
  responsive_sizer: ^3.2.0
  url_launcher: ^6.1.14
  pinput: ^3.0.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  local_auth: ^2.1.6
  flutter_svg_provider: ^1.0.6
  intl: ^0.18.1
  fl_chart: ^0.64.0
  image_picker: ^1.0.4
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#000"
  adaptive_icon_foreground: "assets/icon/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icon/

  fonts:
    - family: hell
      fonts:
        - asset: assets/fonts/Helvetica.ttf
          style: normal
        - asset: assets/fonts/Helvetica-Oblique.ttf
          style: italic
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700
        - asset: assets/fonts/helvetica-light.ttf
          weight: 300
        - asset: assets/fonts/Helvetica-BoldOblique.ttf
          weight: 700
          style: italic
